module.exports = Marty.createConstants(
	[	"SIGNIN_REQUEST",
    "SIGNIN_RESPONSE",
    "SIGNUP_REQUEST",
    "SIGNUP_RESPONSE",
    "SIGNOUT",
    "RESET_PW_RESPONSE",
    "RESEND_CONFIRM_EMAIL_RESPONSE",
    "TRANSITIONTOHOME",
    "TRANSITIONTOPROFILE",
    "TRANSITIONTOSIGNUP"
	]
);